apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: crud-service
  description: web services with spring boot
  tags:
    - spring-boot
    - web-services
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: EMC-Backstage/spring-boot
spec:
  type: service
  lifecycle: development
  owner: frontend-team
  system: web-platform
